/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:1a124e1b-27b1-4eaf-a4d0-7f15cd798032",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_G576hbE2K",
    "aws_user_pools_web_client_id": "5k4mu8qrlphnhe5gonlv4ksq6e",
    "oauth": {},
    "aws_cognito_login_mechanisms": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_appsync_graphqlEndpoint": "https://e3xkzqkxmrdbzhlrfrksbrd37q.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-aovnbaqdn5a2lcugwwlqbrwlny",
    "aws_user_files_s3_bucket": "imagereactfirstapp15357-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
